# Hey there! I absolutely love open sourcing and AmputatorBot, but it costs me €8.26 per month to host the bot 24/7.
# This isn't much, obviously. But it adds up quickly.

# This link will direct you to my PayPal donation page, where you can fill in any amount you want.
# Just remember that I'm only trying to cover the costs ;)
# Massive thx! 

custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EU6ZFKTVT9VH2&source=url
