# Hi there! The bot and website cost approximately €8.26 a month to host and while that might not seem like much,
# it adds up. All donations will ONLY be used to pay for hosting. You can specify any amount you want, but please
# keep in mind that I only want to try to cover some of the costs. Thank you so much!

custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EU6ZFKTVT9VH2
