# The bots, website and API cost about 10 euros (12 dollars) per month to host.
# I will use all donations strictly to break even.
# You can donate any amount via PayPal, GitHub Sponsors or with crypto (see comments below). Thank you so much!

# Bitcoin (BTC): 1GsspnGwbaXfMP2P6t9Hr5oQwCYZdsPHr
# Cardano (ADA): DdzFFzCqrht1gHfopZ7ddXfJFz9tXkhQERc6dzfP71Ve9NoJYk4jQ1wtW1LNCWokMPoDZ7xr7YvHqvt82tG3MsEukkkcQyvUxrwjLWqx
# Dogecoin (DOGE): D8T2QaHiyUSNRvbu2D4L1W44Ge8NPtpPgy
# BNB, ETH & Binance Smart Chain (BEP20): 0xa705c939c7537984f41e0ad07c5dc3e60ca53691

github: KilledMufasa
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EU6ZFKTVT9VH2
