# The server for the bot, website, and API costs about €10 ($12) per month.
# If you support AmputatorBot's mission and can chip in, any donation would be a huge help.
# Every bit goes straight into server expenses. Or, donate to our friends in Ukraine instead! Thanks a bunch! - AmputatorBot's human

github: KilledMufasa
custom: [https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EU6ZFKTVT9VH2, https://savelife.in.ua/en/donate-en/#donate-army-card-monthly, https://u24.gov.ua/]
